import { Talk } from "@/types";

export const TALK_TYPES = [
  "Conference",
  "Workshop",
  "Meetup",
  "Webinar",
  "Podcast",
];

export const Talks: Talk[] = [
  {
    featured: true,
    title: "Server Components, What's that?",
    host: "React Africa",
    country: "🇲🇦",
    city: "Casablanca",
    talkType: "Conference",
    hostLink: "https://react-africa.com/",
    pictures: [
      "react-africa/demo.jpeg",
      "react-africa/left-angle.jpg",
      "react-africa/smiling.jpeg",
      "react-africa/in-motion.jpg",
      "react-africa/lineup.jpg",
    ],
    date: "November 29, 2024",
    duration: "30min.",
    slides:
      "https://docs.google.com/presentation/d/1f6527uoa7hDLc4f_gT9kYI9xge5qsPx7nMEW8eLxJyI/edit?usp=sharing",
    demoCode: "https://github.com/choubari/react-server-components-101-demo",
    demoLink: "https://react-server-components-101-demo.vercel.app/",
  },
  {
    title: "5 bonnes pratiques pour améliorer votre code React",
    host: "Packmind",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    hostLink:
      "https://www.linkedin.com/posts/cedricteyton_et-si-on-parlait-de-bonnes-pratiques-react-activity-7257402202837688321-7xFR",
    pictures: ["others/packmind/webinar-flyer.jpg"],
    date: "November 7, 2024",
    duration: "60min.",
    video: "https://youtu.be/6s_T8mlt0_Y",
  },
  {
    featured: true,
    title: "React Server Components 101",
    host: "ReactJS Day",
    country: "🇮🇹",
    city: "Verona",
    talkType: "Conference",
    hostLink:
      "https://2024.reactjsday.it/talks_speakers/#ReactServerComponents101",
    pictures: ["reactjs-day/full-room.png"],
    date: "October 25, 2024",
    duration: "45min.",
    slides:
      "https://docs.google.com/presentation/d/1f6527uoa7hDLc4f_gT9kYI9xge5qsPx7nMEW8eLxJyI/edit?usp=sharing",
    demoCode: "https://github.com/choubari/react-server-components-101-demo",
    demoLink: "https://react-server-components-101-demo.vercel.app/",
  },
  {
    featured: true,
    title: "React Server Components Deep Dive",
    host: "O'Reilly Media",
    country: "🌐",
    city: "Online",
    talkType: "Workshop",
    hostLink:
      "https://www.oreilly.com/live-events/react-server-components-deep-dive/0642572003766/",
    pictures: [
      "oreilly-media/oreilly-event-page.png",
      "oreilly-media/ReactServerComponentsCourse-oreilly.png",
    ],
    date: "August 28, 2024",
    duration: "180min.",
  },
  {
    title: "React Server Components 101",
    host: "React Paris Meetup",
    country: "🇫🇷",
    city: "Paris",
    talkType: "Meetup",
    hostLink: "https://www.meetup.com/react-paris/events/300756193/",
    pictures: ["react-paris/react-paris-meetup.png"],
    date: "May 28, 2024",
    duration: "25min.",
  },
  {
    title: "DevRel and tech talks",
    host: "GeeksBlaBla #177",
    country: "🌐",
    city: "Online",
    talkType: "Podcast",
    hostLink:
      "https://geeksblabla.community/podcast/devrel-and-tech-talks.html",
    pictures: ["geeksblabla/devrel-tech-talks.jpg"],
    date: "April 21, 2024",
    duration: "195min.",
    video: "https://www.youtube.com/live/8uKEwWbgRBc",
  },
  {
    featured: true,
    title: "React Server Components 101",
    host: "Devoxx France",
    country: "🇫🇷",
    city: "Paris",
    talkType: "Conference",
    hostLink: "https://www.devoxx.fr/schedule/talk/?id=47585",
    pictures: ["devoxx-france/in-motion.png"],
    date: "April 18, 2024",
    duration: "25min.",
    slides:
      "https://docs.google.com/presentation/d/1MQTIpdAl9wTceNu2QrZaa-TmRFeng-qPWPCJiDnGzrY/edit?usp=sharing",
    demoCode: "https://github.com/choubari/react-server-components-101-demo",
    demoLink: "https://react-server-components-101-demo.vercel.app/",
    video: "https://youtu.be/sPoo1Zwh64w",
  },
  {
    featured: true,
    title: "Partial Prerendering: Hype or Innovation?",
    host: "React Paris",
    country: "🇫🇷",
    city: "Paris",
    talkType: "Conference",
    hostLink: "https://react.paris/",
    pictures: [
      "react-paris/full-room.png",
      "react-paris/left-angle.jpg",
      "react-paris/reactparis-lineup.png",
    ],
    date: "March 22, 2024",
    duration: "30min.",
    slides:
      "https://docs.google.com/presentation/d/1ZYtCOUfGCvUO5kFDbFWoGsmJbIJrHGnimuS_4WsKkEI/edit?usp=sharing",
    demoCode: "https://github.com/choubari/partial-prerendering-demo",
    demoLink: "https://partial-pre-rendering.vercel.app/",
    video: "https://youtu.be/1Xplez2KRaI",
  },
  {
    title: "React Server Components 101",
    host: "Devoxx Morocco",
    country: "🇲🇦",
    city: "Agadir",
    talkType: "Conference",
    hostLink: "https://devoxx.ma/",
    pictures: ["devoxx-morocco/2023/ReactServerComponents101-devoxxma.jpg"],
    date: "October 11, 2023",
    duration: "25min.",
    slides:
      "https://docs.google.com/presentation/d/1mYwfi_P9fHbgvyEp4WTa6cLGKZX9RTybXERWozZWneE/edit?usp=sharing",
    demoCode: "https://github.com/choubari/react-server-components-101-demo",
    demoLink: "https://react-server-components-101-demo.vercel.app/",
  },
  {
    featured: true,
    title: "Modern Web Development with Next.js 13",
    host: "Devoxx Morocco",
    country: "🇲🇦",
    city: "Agadir",
    talkType: "Workshop",
    hostLink: "https://devoxx.ma/",
    pictures: ["devoxx-morocco/2023/nextjs-react-framework-devoxxma.jpg"],
    date: "October 11, 2023",
    duration: "120min.",
    slides:
      "https://docs.google.com/presentation/d/1c8pyShj8qoVipXYH2s2Wc7DT8DetBGpDAGnTlBhscJ4/edit?usp=sharing",
    demoCode: "https://github.com/choubari/RSVP-Event-App",
    demoLink: "https://rsvp.choubari.com/",
    docs: "https://nextjs.choubari.com/",
  },
  {
    title: "Back To School",
    host: "GeeksBlaBla #155",
    country: "🌐",
    city: "Online",
    talkType: "Podcast",
    hostLink: "https://geeksblabla.community/podcast/back-to-school",
    pictures: ["geeksblabla/backtoschool.jpg"],
    date: "September 3, 2023",
    duration: "90min.",
    video: "https://www.youtube.com/live/Q688u-Y44tU?si=uHMYPJpnLQ29uFI4",
  },
  {
    title: "Next.js 13, what's going on?",
    host: "Biztech Morocco",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    hostLink:
      "https://www.linkedin.com/feed/update/urn:li:activity:7065016707844591616?utm_source=share",
    pictures: ["others/biztech/nextjs-biztech.jpg"],
    date: "May 20, 2023",
    duration: "120min.",
    video: "https://www.youtube.com/live/s4sdXK4ApKM?feature=share",
    slides:
      "https://docs.google.com/presentation/d/1fQrKxUaWN14whNxxydmua8DRrhW8etvz4cf_1CuX4EY/edit?usp=share_link",
    demoCode: "https://github.com/choubari/Nextjs13-Demo-App",
    demoLink: "https://nextjs13-demo-app.vercel.app/",
  },
  {
    title: "AMA & Tech News #23",
    host: "GeeksBlaBla",
    country: "🌐",
    city: "Online",
    talkType: "Podcast",
    hostLink: "https://geeksblabla.community/podcast/tech-news--ama-23",
    pictures: ["geeksblabla/ama-23.jpg"],
    date: "March 27, 2023",
    duration: "150min.",
    video: "https://www.youtube.com/live/0x1a-7JK_co?si=XqwXQqOKRKV67w6i",
  },
  {
    title: 'How to make a "perfect" git commit',
    host: "Blabla Conf",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    hostLink: "https://www.blablaconf.com/",
    pictures: ["geeksblabla/gitcommit-blablaconf.jpg"],
    date: "December 21, 2022",
    duration: "25min.",
    video: "https://youtu.be/-_kW5E4gGHA",
    slides:
      "https://docs.google.com/presentation/d/14bfZYD1JQni5mBJSB6kh-bIA3mUudwQKJ9wDYMbN-0E/edit?usp=share_link",
    demoCode:
      "https://gist.github.com/choubari/c89b685c334939d581489c537b5bda2f",
  },
  {
    title: "Best Practices for Better Accessibility",
    host: "ISoc Accessibility Standing Group",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    hostLink: "https://www.a11ysig.org/accessniger/",
    pictures: [
      "others/isoc-a11y/a11y-isoc-flyer.jpg",
      "others/isoc-a11y/a11y-isoc.jpg",
    ],
    date: "November 12, 2022",
    duration: "50min.",
    video:
      "https://livestream.com/accounts/686369/events/10680706/videos/233733279",
    slides:
      "https://docs.google.com/presentation/d/1YhI28l_MbckArNvUB1rcoMglVh-FyCUjDULGaqW9-oE/edit?usp=sharing",
  },
  {
    title: "Best Practices for Better Accessibility",
    host: "Devoxx Morocco",
    country: "🇲🇦",
    city: "Agadir",
    talkType: "Conference",
    hostLink: "https://devoxx.ma/talk/?id=10482",
    pictures: [
      "devoxx-morocco/2022/a11y-devoxxma-footage.jpg",
      "devoxx-morocco/2022/a11y-devoxxma.jpg",
    ],
    date: "October 6, 2022",
    duration: "50min.",
    slides:
      "https://docs.google.com/presentation/d/1Mnm6vPXKHaKOsHMU-Su3H0IEaU4eGmYLVjcvbLED98s/edit?usp=share_link",
  },
  {
    title: 'How to make a "perfect" git commit',
    host: "Devoxx Morocco",
    country: "🇲🇦",
    city: "Agadir",
    talkType: "Conference",
    hostLink: "https://devoxx.ma/talk/?id=10481",
    pictures: [
      "devoxx-morocco/2022/gitcommit-devoxxma-footage.jpg",
      "devoxx-morocco/2022/gitcommit-devoxxma.jpg",
    ],
    date: "October 5, 2022",
    duration: "25min.",
    slides:
      "https://docs.google.com/presentation/d/1xgV9YQSQX05gEyEvYpWzwiXRdGCeXHztN57rN3q4yec/edit?usp=share_link",
    demoCode:
      "https://gist.github.com/choubari/c89b685c334939d581489c537b5bda2f",
  },
  {
    title: "AMA & Tech News #15",
    host: "GeeksBlaBla",
    country: "🌐",
    city: "Online",
    talkType: "Podcast",
    hostLink: "https://geeksblabla.community/podcast/tech-news--ama-15",
    pictures: ["geeksblabla/ama-15.jpg"],
    date: "January 30, 2022",
    duration: "120min.",
    video: "https://www.youtube.com/live/4_h-lxi3GlU?si=3HSQm7TMOAgsGsoH",
  },
  {
    title: "Introduction to Game Dev",
    host: "ENSIAS IT Club",
    country: "🌐",
    city: "Online",
    talkType: "Podcast",
    hostLink:
      "https://www.linkedin.com/feed/update/urn:li:activity:6871566461639368704/",
    pictures: ["others/school-clubs/gamedev-ittalk.jpg"],
    date: "December 2, 2021",
    duration: "60min.",
    video: "https://www.youtube.com/live/CforaDN-3Do?feature=share",
  },
  {
    title: "A Guide to Academic Report Writing with LaTeX",
    host: "IEEE ENSIAS Student Branch",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    hostLink:
      "https://twitter.com/EnsiasSb/status/1349696348606652421?t=asi7OMRJUtanYaXag41ncA&s=08",
    pictures: ["others/school-clubs/latex-ieee.jpg"],
    date: "January 14, 2021",
    duration: "120min.",
    slides:
      "https://docs.google.com/presentation/d/1Xumg0GKqeNrrJ-TqYTYnGEOCbI3Gce3ZFwDxE0HtJ2c/edit?usp=share_link",
  },
  {
    title: "Get started with Git & Github",
    host: "IEEE ENSIAS Student Branch",
    country: "🌐",
    city: "Online",
    talkType: "Webinar",
    pictures: ["others/school-clubs/git-ieee.jpg"],
    date: "January 12, 2021",
    duration: "120min.",
    slides:
      "https://docs.google.com/presentation/d/1mB79ojRZ05DWhxx4fUV1gK2z6JW_1Z7gB7xEf_YaTn8/edit?usp=share_link",
  },
];
