import { Nav } from "@/components/nav";
import "./globals.css";
import { Providers } from "@/lib/provider";
import Footer from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light dark:bg-darker text-darker dark:text-lighter">
        <Providers>
          <Nav />
          <div className="mx-auto lg:max-w-7xl">{children}</div>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
