import { Nav } from "@/components/nav";
import "./globals.css";
import { Providers } from "@/lib/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light dark:bg-darker text-darker dark:text-lighter">
        <Providers>
          <Nav />
          {children}
        </Providers>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
